daily-rewards:

  1:
    slimefun: ELECTRIC_MOTOR
    amount: 2

  2:
    slimefun: BATTERY
    amount: 4

  3:
    slimefun: SOLAR_PANEL
    amount: 1

  4:
    slimefun: BRONZE_INGOT
    amount: 16

  5:
    slimefun: STEEL_INGOT
    amount: 8

  6:
    slimefun: REINFORCED_ALLOY_INGOT
    amount: 2

  7:
    slimefun: MAGIC_LUMP_3
    amount: 1
